name: CI

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
      - name: Check if code is formatted
        run: |
          v fmt -diff .
          v fmt -verify .
      - name: Build ${{ github.event.repository.name }}
        run: v .
